### ISSUE TITLE
Re-work logic for last child border on multiple exceptional opening times on desktop a/ similar to mobile

### ISSUE THREAD

**Issue by beseven** [nhsuk/profiles#146]
<img width="815" alt="screen shot 2017-05-25 at 16 05 27" src="https://cloud.githubusercontent.com/assets/1902266/26485146/b6d3a1f2-41ed-11e7-8bfd-88383d1621b1.png">
<img width="388" alt="screen shot 2017-05-25 at 16 07 09" src="https://cloud.githubusercontent.com/assets/1902266/26485147/b7bf3b80-41ed-11e7-91ea-39b33282c26c.png">

**Comment by ajthomascouk** [comment]
New PR (https://github.com/nhsuk/profiles/pull/148) fixing this issue.

**Comment by neilbmclaughlin** [comment]
Looks like this issue was fixed.
